logs:
  level: 20
  tensorboard_path: "./logs/tensorboard"

accelerator: gpu
devices: 1
num_workers: 71

assets:
  path: ./assets
  piece_sets: []

checkpoints:
  path: ./checkpoints

output:
  path: ./output

dataset:
  path: ./datasets

  augmentations:
    AugmentedBoardsImages:
      bg: {}
      board: {}
      final: {}

    AugmentedPiecesImages: {}

  sections:
    championships:
      download_url_template: https://www.pgnmentor.com/events/{name}.pgn
      names:
        - WorldChamp2021

    players:
      download_url_template: https://www.pgnmentor.com/players/{name}.zip
      names:
        - Adams
        - Akobian
        - Akopian
        - Alburt
        - Alekhine
        - Alekseev
        - Almasi
        - Anand
        - Anderssen
        - Andersson
        - Andreikin
        - Aronian
        - Ashley
        - Averbakh
        - Azmaiparashvili
        - Bacrot
        - Bareev
        - BecerraRivero
        - Beliavsky
        - Benjamin
        - Benko
        - Berliner
        - Bernstein
        - Bird
        - Bisguier
        - Blackburne
        - Blatny
        - Bogoljubow
        - Boleslavsky
        - Bologan
        - Botvinnik
        - Breyer
        - Bronstein
        - Browne
        - Bruzon
        - Bu
        - Byrne
        - Capablanca
        - Carlsen
        - Caruana
        - Chiburdanidze
        - Chigorin
        - Christiansen
        - DeFirmian
        - DeLaBourdonnais
        - Denker
        - Ding
        - DominguezPerez
        - Dreev
        - Duda
        - Dzindzichashvili
        - Ehlvest
        - Eljanov
        - Euwe
        - Evans
        - Fedorowicz
        - Fine
        - Finegold
        - Firouzja
        - Fischer
        - Fishbein
        - Flohr
        - Gaprindashvili
        - Gashimov
        - Gelfand
        - Geller
        - Georgiev
        - Giri
        - Gligoric
        - Goldin
        - GrandaZuniga
        - Grischuk
        - Gulko
        - Gunsberg
        - GurevichD
        - GurevichM
        - Harikrishna
        - Hort
        - Horwitz
        - Hou
        - Huebner
        - Ibragimov
        - IllescasCordoba
        - Inarkiev
        - Ivanchuk
        - IvanovA
        - IvanovI
        - Ivkov
        - Jakovenko
        - Janowski
        - Jobava
        - Jussupow
        - Kaidanov
        - Kamsky
        - Karjakin
        - Karpov
        - Kasimdzhanov
        - Kasparov
        - Kavalek
        - Keres
        - Khalifman
        - Kholmov
        - Koneru
        - Korchnoi
        - Korobov
        - Kosteniuk
        - Kotov
        - Kramnik
        - Krasenkow
        - Krush
        - Kudrin
        - Lahno
        - Larsen
        - Lasker
        - Lautier
        - Le
        - Leko
        - Levenfish
        - Li
        - Lilienthal
        - Ljubojevic
        - Lputian
        - MacKenzie
        - Malakhov
        - Mamedyarov
        - Maroczy
        - Marshall
        - McDonnell
        - McShane
        - Mecking
        - Mikenas
        - Miles
        - Milov
        - Morozevich
        - Morphy
        - Motylev
        - Movsesian
        - Muzychuk
        - Najdorf
        - Najer
        - Nakamura
        - Navara
        - Negi
        - Nepomniachtchi
        - Ni
        - Nielsen
        - Nikolic
        - Nimzowitsch
        - Nisipeanu
        - Novikov
        - Nunn
        - Olafsson
        - Oll
        - Onischuk
        - Pachman
        - Paehtz
        - Panno
        - Paulsen
        - Petrosian
        - Philidor
        - Pillsbury
        - Pilnik
        - PolgarJ
        - PolgarS
        - PolgarZ
        - Polugaevsky
        - Ponomariov
        - Portisch
        - Psakhis
        - Quinteros
        - Radjabov
        - Rapport
        - Reshevsky
        - Reti
        - Ribli
        - Rohde
        - Rubinstein
        - Rublevsky
        - Saemisch
        - Sakaev
        - Salov
        - Sasikiran
        - Schlechter
        - Seirawan
        - Serper
        - Shabalov
        - Shamkovich
        - Shirov
        - Short
        - Shulman
        - Smirin
        - Smyslov
        - So
        - Sokolov
        - Soltis
        - Spassky
        - Speelman
        - Spielmann
        - Stahlberg
        - Staunton
        - Stefanova
        - Stein
        - Steinitz
        - Suetin
        - SultanKhan
        - Sutovsky
        - Svidler
        - Szabo
        - Taimanov
        - Tal
        - Tarrasch
        - Tartakower
        - Teichmann
        - Timman
        - Tiviakov
        - Tkachiev
        - Tomashevsky
        - Topalov
        - TorreRepetto
        - Uhlmann
        - Unzicker
        - Ushenina
        - VachierLagrave
        - Vaganian
        - VallejoPons
        - VanWely
        - Vitiugov
        - Volokitin
        - Waitzkin
        - Wang
        - WangH
        - Wei
        - Winawer
        - Wojtaszek
        - Wojtkiewicz
        - Wolff
        - Xie
        - Xu
        - Ye
        - Yermolinsky
        - Yu
        - Yudasin
        - Zhu
        - Zukertort
        - Zvjaginsev