[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "chessml"
version = "0.1.1"
authors = [
    { name = "Artem Legotin", email = "arlegotin@gmail.com" },
]
description = "A Python package for advanced chess analysis"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "chess>=1.9.4",
    "tensorboard>=2.12.0",
    "scikit-learn>=1.2.1",
    "matplotlib>=3.7.1",
    "lightning>=2.2.4",
    "torch>=2.0.1",
    "stockfish @ git+https://github.com/py-stockfish/stockfish.git@ba93cf219d705be625f649181660d2ebbf130045",
    "fenToBoardImage>=1.4.1",
    "opencv-python>=4.9.0",
    "torchvision>=0.18.0",
    "timm>=0.9.16",
    "omegaconf>=2.3.0",
    "torchmetrics>=1.4.0.post0",
    "ortools>=9.14.6206",
    "numpy>=2.2.5",
    "Pillow>=12.3.0",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]

[project.urls]
Homepage = "https://github.com/arlegotin/chessml"

[dependency-groups]
dev = [
    "pytest>=5.2",
]

[tool.setuptools.packages.find]
include = ["chessml*"]
namespaces = true

[tool.uv]
required-version = ">=0.6.14"
